spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/springtest
    username: sujin.v2px
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
